export * from "./Home";
export * from "./Register";
export * from "./Login";
export * from "./Dashboard";
export * from "./CheckCode";
export * from "./Profile";
export * from "./ForgotPassword";
export * from "./FormProfile";
export * from "./FigureUserPage";
